window:

  dimensions:
    columns: 100
    lines: 80
  padding:
    x: 2
    y: 2
  # Make padding even
  dynamic_padding: true
  opacity: 0.92

font:
  normal:
    family: 'Cascadia Code'
  bold:
    family: 'Cascadia Code'
  italic:
    family: 'Cascadia Code'
  bold_italic:
    family: 'Cascadia Code'
  size: 12.0


colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5c4a1'

  # Colors the cursor will use if custom_cursor_colors is true
  cursor:
    text: '0x32302f'
    cursor: '0xd5c4a1'



  # Normal colors
  normal:
    black:   '0x32302f'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xfbf1c7'

  indexed_colors:
    - { index: 16, color: '0xfe8019' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3c3836' }
    - { index: 19, color: '0x504945' }
    - { index: 20, color: '0xbdae93' }
    - { index: 21, color: '0xebdbb2' }
