#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV
bspc config focused_border_color "#98971a"

$HOME/.config/polybar/launch.sh --forest
feh --bg-fill $HOME/Wallpapers/philipp-a-urlich-cpncept398-b.jpg
picom &

bspc config border_width         4
bspc config window_gap           8
bspc config top_padding		 32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
