#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="Cascadia Code" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=5 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=off

# Setting up the general bar appearance and default values
sketchybar --bar     height=26                                         \
                     color=$BAR_COLOR                                  \
                     position=top                                      \
                     sticky=on                                         \
                     padding_right=$((10 - $PADDINGS))                 \
                     padding_left=15                                   \
                     corner_radius=4                                   \
                     margin=0                                          \
                     blur_radius=45                                    \
                     notch_width=0                                     \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:14.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=4                  \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/window_app.sh"

# Center
source "$ITEM_DIR/spotify.sh"

# Right

source "$ITEM_DIR/cal_clock.sh"
source "$ITEM_DIR/cal_date.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."

